import Breadcumb from '@/components/breadcumb/Breadcumb'
import DetailFood from '@/components/detailFood/DetailFood'
import Head from 'next/head'
import React from 'react'
import styled from 'styled-components'

const Header = styled.header`
    position: relative !important;
    height: 80px;
`;

const MenuCatering = () => {
    return (
        <>
            <Head>
                <title>Food Detail</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <Breadcumb></Breadcumb>
            <DetailFood></DetailFood>
        </>
    )
}

export default MenuCatering
