import About from '@/components/about/About'
import Chef from '@/components/chef/Chef'
import Hero from '@/components/hero/Hero'
import Menu from '@/components/menu/Menu'
import Popular from '@/components/popular/Popular'
import Service from '@/components/service/Service'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Catering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <Popular></Popular>
      <Service></Service>
      <About></About>
      <Menu></Menu>
      <Chef></Chef>
    </>
  )
}
